wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: random
