wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 100
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
