wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 15
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0.5
weight_init:
  value: xavier
