_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 256
epochs:
    value: 100
hidden_size:
    value: 32
learning_rate:
    value: 0.01
loss:
    value: cross_entropy
num_layers:
    value: 3
optimizer:
    value: momentum
weight_decay:
    value: 0
weight_init:
    value: random
