_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 15
hidden_size:
    value: 256
learning_rate:
    value: 0.0001
loss:
    value: cross_entropy
num_layers:
    value: 4
optimizer:
    value: adam
weight_decay:
    value: 0.5
weight_init:
    value: xavier
