wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 4
epochs:
  value: 100
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: xavier
