wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_init:
  value: random
