wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 5
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: random
