wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
epochs:
  value: 3
hidden_size:
  value: 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: random
