wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 256
dataset:
  value: mnist
epochs:
  value: 30
hidden_size:
  value: 128
learning_rate:
  value: 0.003
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.001
weight_init:
  value: xavier
