wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 30
hidden_size:
  value: 120
learning_rate:
  value: 0.003
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.01
weight_init:
  value: xavier
