wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.005
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
