wandb_version: 1

activation:
  value: relu
batch_size:
  value: 4
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.005
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: xavier
