wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 4
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 120
learning_rate:
  value: 0.005
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: xavier
