wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 15
hidden_size:
  value: 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
