wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 256
epochs:
  value: 100
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
