wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 256
epochs:
  value: 100
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
