wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 15
hidden_size:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
