wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
