wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 15
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: random
