wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 100
hidden_size:
  value: 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
