wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
