wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 15
hidden_size:
  value: 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
