wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 15
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.005
weight_init:
  value: random
