_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: tanh
batch_size:
    value: 256
epochs:
    value: 5
hidden_size:
    value: 64
learning_rate:
    value: 0.001
loss:
    value: mean_squared_error
num_layers:
    value: 4
optimizer:
    value: sgd
weight_decay:
    value: 0
weight_init:
    value: xavier
