wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
