wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 100
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
