wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_init:
  value: random
