wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
