wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 100
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: random
