wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 100
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: random
