wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 15
hidden_size:
  value: 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
